language: nix
matrix:
  include:
    - os: osx
      osx_image: xcode8.3  # 10.12
      script:
      - nix-build ./release.nix -I darwin=. -A tests
      - nix-build ./release.nix -I darwin=. -A examples.simple
      - yes | nix-shell -E 'with import (builtins.fetchGit ./.) {}; installer'
      - nix-shell -A installer.check
      - /run/current-system/sw/bin/darwin-rebuild switch -I darwin=$HOME/.nix-defexpr/channels/darwin -I darwin-config=$HOME/.nixpkgs/darwin-configuration.nix
      - yes | nix-shell -E 'with import (builtins.fetchGit ./.) {}; uninstaller'
      - nix-shell -A uninstaller.check
